#!/usr/bin/python3


# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301 USA

import sys
import os
import errno
import re
import pwd
import sys
import string
import subprocess
import getopt
from stat import *
import argparse
import apt

#
allFiles = False
onlyPackageFiles = False

if os.getuid() != 0:
    sys.stderr.write('ERROR: This program must be run as root in order to obtain information\n')
    sys.stderr.write('about all open file descriptors in the system.\n')
    sys.exit(1)


def find_cmd(cmd):
    dirs = ['/', '/usr/', '/usr/local/', sys.prefix]
    for d in dirs:
        for sd in ('bin', 'sbin'):
            location = os.path.join(d, sd, cmd)
            if os.path.exists(location):
                return location
    return 1


def systemctl_restart(lservices):
    args_restart = ["systemctl", "restart"] + lservices
    subprocess.check_call(args_restart)


class Process:
    def __init__(self, pid):
        self.pid = pid
        self.files = []
        self.descriptors = []
        self.links = []
        self.program = ''
        self.cgroupname = ''
        self.systemd_servicename = ''
        self.cmdline = ""
        self.cmdline_splitted = []
        try:
            self.program = os.readlink('/proc/%d/exe' % self.pid)
            self.cmdline = open('/proc/%d/cmdline' % self.pid, 'r').read()
            self.cmdline_splitted = self.cmdline.split('\x00')
            # Last character should be null-byte, too, see proc(5)
            if not self.cmdline_splitted[-1]:
                self.cmdline_splitted.pop()
            # if the executable command is an interpreter such as perl/python,
            # we want to find the real program
            m = re.match("^/usr/bin/(perl|python)", self.program)
            if m:
                data = self.cmdline_splitted
                # Spamd sets $0 wrongly, see
                # https://bugzilla.redhat.com/show_bug.cgi?id=755644
                # i.e. the blank after spamd is relevant in case
                # this will be fixed in the future.
                m = re.match("^/usr/sbin/spamd |^spamd ", data[0])
                if m:
                    self.program = "/usr/sbin/spamd"
                else:
                    # Strip first value, the interpreter
                    data.pop(0)
                    # Check if something's left after the interpreter, see #715000
                    if data:
                        # Strip all options following the interpreter, e.g. python's -O
                        m = re.match("^-", data[0])
                        while m:
                            data.pop(0)
                            m = re.match("^-", data[0])
                        if data and data[0]:
                            data = data[0]
                        data = self.which(data)
                        m = re.search(r'^(/usr/\S+)$', data)
                        if m:
                            # store the real full path of script as the program
                            self.program = m.group(1)
            # cgroup
            fncgroup = "/proc/%d/cgroup" % self.pid
            if os.path.isfile(fncgroup):
                for cgroupline in open(fncgroup).readlines():
                    if cgroupline.find("1:name=") == 0:
                        cgroupline = cgroupline.rstrip()
                        self.cgroupname = cgroupline[len("1:name="):]
                        if self.cgroupname.find("systemd:/system.slice/") != -1:
                            self.systemd_servicename = self.cgroupname.split("/")[-1]
        except OSError as e:
            if e.errno != errno.ENOENT:
                if self.pid == 1:
                    sys.stderr.write("Found unreadable pid 1. Assuming we're under vserver and continuing.\n")
                else:
                    sys.stderr.write('ERROR: Failed to read %d' % self.pid)
                    raise
        self.program = self.cleanFile(self.program)

    def which(self, program):
        if os.path.isabs(program):
            return program
        path = os.environ.get("PATH", os.defpath).split(os.pathsep)
        seen = set()
        for adir in path:
            adir = os.path.normcase(os.path.abspath(adir))
            if adir not in seen:
                seen.add(adir)
                name = os.path.join(adir, program)
                if os.path.exists(name) and os.access(name, os.F_OK | os.X_OK) and not os.path.isdir(name):
                    return name
        return program

    def clean_file(self, f):
        # /proc/pid/exe has all kinds of junk in it sometimes
        null = f.find('\0')
        if null != -1:
            f = f[:null]
        # Support symlinked /usr
        if f.startswith('/usr'):
            statinfo = os.lstat('/usr')[ST_MODE]
            # If /usr is a symlink then find where it points to
            if S_ISLNK(statinfo):
                newusr = os.readlink('/usr')
                if not newusr.startswith('/'):
                    # If the symlink is relative, make it absolute
                    newusr = os.path.join(os.path.dirname('/usr'), newusr)
                f = re.sub('^/usr', newusr, f)
                # print "Changing usr to " + newusr + " result:" +f; # Debugging
        return re.sub('( \(deleted\)|.dpkg-new).*$', '', f)

    def list_deleted(self):
        return [f for f in self.files if isdeletedFile(f)]

    # Check if a process needs to be restarted, previously we would
    # just check if it used libraries named '.dpkg-new' since that's
    # what dpkg would do. Now we need to be more contrieved.
    # Returns:
    #  - 0 if there is no need to restart the process
    #  - 1 if the process needs to be restarted
    def needsRestart(self, blacklist=None):
        if not self.systemd_servicename:
            return 0
        for f in self.files:
            if isdeletedFile(f, blacklist):
                return 1
        for f in self.links:
            if f == 0:
                return 1
        return 0

    def restartIt(self):
        systemctl_restart([self.systemd_servicename])


def lsofcheck(blacklist=None):
    processes = {}
    #
    for line in subprocess.check_output(['lsof', '+L', '-X', '-F', 'nfpk']).decode().splitlines():
        field, data = line[0], line[1:]

        if field == 'p':
            process = processes.setdefault(data, Process(int(data)))
        elif field == 'k':
            process.links.append(data)
        elif field == 'n':
            # Remove the previous entry to check if this is something we should use
            if data.startswith('/SYSV'):
                # If we find SYSV we discard the previous descriptor
                last = process.descriptors.pop()
            elif data.startswith('/'):
                last = process.descriptors.pop()
                # Add it to the list of deleted files if the previous descriptor
                # was DEL or lsof marks it as deleted
                if re.compile("DEL").search(last) or re.compile("deleted").search(data) or re.compile(
                        "\(path inode=[0-9]+\)$").search(data):
                    process.files.append(data)
            else:
                # We discard the previous descriptors and drop it
                last = process.descriptors.pop()
        elif field == 'f':
            # Save the descriptor for later comparison
            process.descriptors.append(data)
    #
    lto_restart = []
    for process in processes.values():
        if process.needsRestart(blacklist):
            lto_restart.append(process)
    return lto_restart


def isdeletedFile(f, blacklist=None):
    global lc_all_c_env, file_query_check

    if allFiles:
        return 1
    if blacklist:
        for p in blacklist:
            if p.search(f):
                return 0
    # We don't care about log files
    if f.startswith('/var/log/') or f.startswith('/var/local/log/'):
        return 0
    # Or about files under temporary locations
    if f.startswith('/var/run/') or f.startswith('/var/local/run/'):
        return 0
    # Or about files under /tmp
    if f.startswith('/tmp/'):
        return 0
    # Or about files under /dev/shm
    if f.startswith('/dev/shm/'):
        return 0
    # Or about files under /run
    if f.startswith('/run/'):
        return 0
    # Or about files under /drm
    if f.startswith('/drm'):
        return 0
    # Or about files under /var/tmp and /var/local/tmp
    if f.startswith('/var/tmp/') or f.startswith('/var/local/tmp/'):
        return 0
    # Or /dev/zero
    if f.startswith('/dev/zero'):
        return 0
    # Or /dev/pts (used by gpm)
    if f.startswith('/dev/pts/'):
        return 0
    # Or /usr/lib/locale
    if f.startswith('/usr/lib/locale/'):
        return 0
    # Skip files from the user's home directories
    # many processes hold temporafy files there
    if f.startswith('/home/'):
        return 0
    # Skip automatically generated files
    if f.endswith('icon-theme.cache'):
        return 0
    # Skip font files
    if f.startswith('/var/cache/fontconfig/'):
        return 0
    # Skip Nagios Spool
    if f.startswith('/var/lib/nagios3/spool/'):
        return 0
    # Skip nagios spool files
    if f.startswith('/var/lib/nagios3/spool/checkresults/'):
        return 0
    if f.startswith('/var/lib/logstash'):
        return 0
    # skip conflunce
    if f.startswith('/var/atlassian/application-data/confluence/index/edge/'):
        return 0
    # skip Asynchronous I/O
    if f == "/[aio]":
        return 0
    # Skip, if asked to, files that do not belong to any package
    if onlyPackageFiles:
        # Remove some lsof information from the file to ensure that it is
        # a proper filename
        file_name = re.sub(r'\(.*\)', '', f)
        file_name = re.sub(r'\s+$', '', file_name)
        # First check: have we checked this file before? If we have not then make the check
        if not file_name in file_query_check:
            file_query_check[file_name] = ispackagedFile(file_name)
        # Once we have the result then check if the file belongs to a package
        if not file_query_check[file_name]:
            return 0

    # TODO: it should only care about library files (i.e. /lib, /usr/lib and the like)
    # build that check with a regexp to exclude others
    if f.endswith(' (deleted)'):
        return 1
    if re.compile("\(path inode=[0-9]+\)$").search(f):
        return 1
    # Default: it is a deleted file we are interested in
    return 1


def get_list_of_processes(blacklist):
    if find_cmd('lsof') == 1:
        print('ERROR: This program needs lsof in order to run', file=sys.stderr)
        print('Please install the lsof package in your system', file=sys.stderr)
        print('Exit !', file=sys.stderr)
        sys.exit(1)
    # Check if we have lsof, if not, use psdel
    #    if find_cmd('lsof'):
    #         toRestart = lsofcheck()
    #    else:
    # TODO - This does not work yet:
    #        toRestart =     psdelcheck()

    # find processus which has a old file
    lprocess_to_restart = lsofcheck(blacklist=blacklist)
    #
    # remove some processus
    lprocess_to_restart = [p for p in lprocess_to_restart if p.cmdline_splitted[0].find("sshd:") != 0]

    def key_process(a):
        return a.pid

    lprocess_to_restart.sort(key=key_process)
    return lprocess_to_restart


def check(blacklist=[], is_verbose=False):
    lprocess = get_list_of_processes(blacklist)
    for process in lprocess:
        print(process.pid, process.systemd_servicename, process.cgroupname, process.program)
        if is_verbose:
            lfilename_deleted = process.list_deleted()
            if lfilename_deleted:
                print("  list of deleted files:")
                for filename in lfilename_deleted:
                    print("    {}".format(filename))
    if not lprocess:
        sys.exit()


def needs_restart(blacklist=[]):
    if get_list_of_processes(blacklist):
        print("yes")
    else:
        print("no")


def kernel_needs_restart():
    linux_release = os.uname().release
    package_name = "linux-image-{}".format(linux_release)
    package = apt.cache.Cache()[package_name]
    RE_STR = "\s{}\s".format(re.escape(package.installed.version))
    match = re.search(RE_STR, os.uname().version)
    if match:
        print("no")
    else:
        print("yes")


def restart(is_verbose=False):
    lprocess = get_list_of_processes([])
    lservicename = [p.systemd_servicename for p in lprocess]
    lservicename = list(set(lservicename))
    if lservicename:
        print("process to be restarted:")
        for servicename in lservicename:
            print("  {}".format(servicename))
        systemctl_restart(lservicename)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='tools that check if deamons must be restarted')
    subparsers = parser.add_subparsers(help="sub-command-help")
    # check
    check_parser = subparsers.add_parser("check", help="check if there is some process to restart")
    check_parser.set_defaults(name="check", func=check)
    check_parser.add_argument("-v", "--verbose", help="increase output verbosity",
                              action="store_true")

    # restart
    restart_parser = subparsers.add_parser("restart", help="restart the process")
    restart_parser.set_defaults(name="restart", func=restart)
    restart_parser.add_argument("-v", "--verbose", help="increase output verbosity",
                                action="store_true")
    # should_restart
    needs_restart_parser = subparsers.add_parser("needs-restart", help="tells if it needs to restart")
    needs_restart_parser.set_defaults(name="needs-restart", func=check)

    # should_restart_kernel
    needs_restart_parser = subparsers.add_parser("kernel-needs-restart", help="tells if it needs to restart")
    needs_restart_parser.set_defaults(name="kernel-needs-restart", func=check)

    # needs
    args = parser.parse_args()
    if hasattr(args, "name"):
        if "check" == args.name:
            check(is_verbose=args.verbose)
        elif "restart" == args.name:
            restart(is_verbose=args.verbose)
        elif "needs-restart" == args.name:
            needs_restart()
        elif "kernel-needs-restart" == args.name:
            kernel_needs_restart()
    else:
        parser.print_help()
